import sharp from 'sharp'
import { mkdir, stat, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'

// All inputs are local runtime assets. No briefing directory is required.
const assets = [
  ['heroMobile', 'hero/hero-mobile.png', [480, 768, 1080]],
  ['heroDesktop', 'hero/hero-desktop.png', [1280, 1920]],
  ['cleito', 'lore/cleito-transparent.png', [480, 800]],
  ['bario', 'community/bario-2026-06-27.jpg', [480, 900]],
  ['brasil', 'community/jogo-brasil-2026-06-29.png', [400, 768]],
  ['coolDoce', 'community/cool-doce-2026-07-12.jpg', [480, 900]],
  ['jogaydev', 'community/jogaydev-2026-07-21.jpg', [480, 960, 1440]],
  ['bento', 'community/happy-hour-bento-2026-07-31.jpg', [480, 900]],
  ['blackMirror', 'community/black-mirror-2026-09-05.jpg', [480, 900]],
]
const assetRoot = new URL('../src/assets/', import.meta.url)
const imports = []
const records = []
let originalBytes = 0
let optimizedBytes = 0
for (const [id, file, requestedWidths] of assets) {
  const input = fileURLToPath(new URL(file, assetRoot))
  const metadata = await sharp(input).metadata()
  const widths = [...new Set(requestedWidths.map((width) => Math.min(width, metadata.width)))].sort((a, b) => a - b)
  const sources = []
  for (const width of widths) {
    const outputFile = `${file.replace(/\.[^.]+$/, '')}-${width}w.webp`
    const result = await sharp(input).rotate().resize({ width, withoutEnlargement: true }).webp({ quality: 84, effort: 6 }).toFile(fileURLToPath(new URL(outputFile, assetRoot)))
    optimizedBytes += result.size
    const variable = `${id}${width}`
    imports.push(`import ${variable} from '../assets/${outputFile}'`)
    sources.push(`{ src: ${variable}, width: ${result.width} }`)
  }
  const originalVar = `${id}Original`
  imports.push(`import ${originalVar} from '../assets/${file}'`)
  // Original is the image fallback; modern browsers select WebP sources.
  records.push(`  ${id}: { src: ${originalVar}, width: ${metadata.width}, height: ${metadata.height}, sources: [${sources.join(', ')}] }`)
  originalBytes += (await stat(input)).size
}
await mkdir(new URL('../src/data/', import.meta.url), { recursive: true })
await writeFile(new URL('../src/data/images.ts', import.meta.url), `// Generated by npm run images from local assets.\nimport type { ImageAsset } from '../types/content'\n${imports.join('\n')}\n\nexport const images = {\n${records.join(',\n')}\n} satisfies Record<string, ImageAsset>\n`)
console.log(`Prepared ${assets.length} local assets. Originals: ${(originalBytes / 1048576).toFixed(2)} MiB; all WebP variants: ${(optimizedBytes / 1048576).toFixed(2)} MiB.`)
