// Generated by npm run images from local assets.
import type { ImageAsset } from '../types/content'
import heroMobile480 from '../assets/hero/hero-mobile-480w.webp'
import heroMobile768 from '../assets/hero/hero-mobile-768w.webp'
import heroMobile941 from '../assets/hero/hero-mobile-941w.webp'
import heroMobileOriginal from '../assets/hero/hero-mobile.png'
import heroDesktop1280 from '../assets/hero/hero-desktop-1280w.webp'
import heroDesktop1672 from '../assets/hero/hero-desktop-1672w.webp'
import heroDesktopOriginal from '../assets/hero/hero-desktop.png'
import cleito480 from '../assets/lore/cleito-transparent-480w.webp'
import cleito800 from '../assets/lore/cleito-transparent-800w.webp'
import cleitoOriginal from '../assets/lore/cleito-transparent.png'
import bario480 from '../assets/community/bario-2026-06-27-480w.webp'
import bario899 from '../assets/community/bario-2026-06-27-899w.webp'
import barioOriginal from '../assets/community/bario-2026-06-27.jpg'
import brasil400 from '../assets/community/jogo-brasil-2026-06-29-400w.webp'
import brasil574 from '../assets/community/jogo-brasil-2026-06-29-574w.webp'
import brasilOriginal from '../assets/community/jogo-brasil-2026-06-29.png'
import coolDoce480 from '../assets/community/cool-doce-2026-07-12-480w.webp'
import coolDoce899 from '../assets/community/cool-doce-2026-07-12-899w.webp'
import coolDoceOriginal from '../assets/community/cool-doce-2026-07-12.jpg'
import jogaydev480 from '../assets/community/jogaydev-2026-07-21-480w.webp'
import jogaydev960 from '../assets/community/jogaydev-2026-07-21-960w.webp'
import jogaydev1440 from '../assets/community/jogaydev-2026-07-21-1440w.webp'
import jogaydevOriginal from '../assets/community/jogaydev-2026-07-21.jpg'
import bento480 from '../assets/community/happy-hour-bento-2026-07-31-480w.webp'
import bento899 from '../assets/community/happy-hour-bento-2026-07-31-899w.webp'
import bentoOriginal from '../assets/community/happy-hour-bento-2026-07-31.jpg'
import blackMirror480 from '../assets/community/black-mirror-2026-09-05-480w.webp'
import blackMirror899 from '../assets/community/black-mirror-2026-09-05-899w.webp'
import blackMirrorOriginal from '../assets/community/black-mirror-2026-09-05.jpg'

export const images = {
  heroMobile: { src: heroMobileOriginal, width: 941, height: 1672, sources: [{ src: heroMobile480, width: 480 }, { src: heroMobile768, width: 768 }, { src: heroMobile941, width: 941 }] },
  heroDesktop: { src: heroDesktopOriginal, width: 1672, height: 941, sources: [{ src: heroDesktop1280, width: 1280 }, { src: heroDesktop1672, width: 1672 }] },
  cleito: { src: cleitoOriginal, width: 1122, height: 1402, sources: [{ src: cleito480, width: 480 }, { src: cleito800, width: 800 }] },
  bario: { src: barioOriginal, width: 899, height: 1600, sources: [{ src: bario480, width: 480 }, { src: bario899, width: 899 }] },
  brasil: { src: brasilOriginal, width: 574, height: 835, sources: [{ src: brasil400, width: 400 }, { src: brasil574, width: 574 }] },
  coolDoce: { src: coolDoceOriginal, width: 899, height: 1600, sources: [{ src: coolDoce480, width: 480 }, { src: coolDoce899, width: 899 }] },
  jogaydev: { src: jogaydevOriginal, width: 1442, height: 1220, sources: [{ src: jogaydev480, width: 480 }, { src: jogaydev960, width: 960 }, { src: jogaydev1440, width: 1440 }] },
  bento: { src: bentoOriginal, width: 899, height: 1600, sources: [{ src: bento480, width: 480 }, { src: bento899, width: 899 }] },
  blackMirror: { src: blackMirrorOriginal, width: 899, height: 1600, sources: [{ src: blackMirror480, width: 480 }, { src: blackMirror899, width: 899 }] }
} satisfies Record<string, ImageAsset>
